// ignore_for_file: prefer_single_quotes, prefer_interpolation_to_compose_strings, use_raw_strings, noop_primitive_operations, unnecessary_statements, unnecessary_parenthesis

import 'dart:convert';
import 'dart:developer';
import 'package:http/http.dart' as http;
import 'package:posproject/Constant/AppConstant.dart';

import '../../Models/ServiceLayerModel/SapSalesQuotation/GetQuotsforPutModel.dart';
import '../../Models/ServiceLayerModel/SapSalesQuotation/SalesQuotPostModel.dart';
import '../../url/url.dart';


class SalesQuotPutAPi {
  static QuotPutModel? quotputaval;
  static String? sessionID;
  static String? cardCodePost;
  static List<DocumentLineData>? docLineQout;
  static String? docDate;
  static String? dueDate;
  static String? remarks;
  static void method(String? deviceTransID) {
    final data = json.encode({
      "CardCode": "$cardCodePost",
      "DocumentStatus": "bost_Open",
      "DocDate": "$docDate",
      "DocDueDate": "$dueDate",
      "Comments": "$remarks",
      "U_DeviceTransID": deviceTransID,
      "DocumentLines": docLineQout!.map((e) => e.toJson()).toList(),
    });
    // log("post q data : " + data.toString());
  }

  static Future<SalesQuotStatus> getGlobalData(
      String? deviceTransID, int docentry) async {
    try {
      log(URL.url + "Quotations($docentry)");
      final response = await http.put(
        //instead of patch
        Uri.parse(
          URL.url + "Quotations($docentry)",
        ),
        headers: {
          "content-type": "application/json",
          "cookie": 'B1SESSION=' + AppConstant.sapSessionID.toString(),
          // "Prefer":"return-no-content"
        },
        body: json.encode({
          'odata.metadata': quotputaval!.odataMetadata,
          'odata.etag': quotputaval!.odataEtag,
          'DocEntry': quotputaval!.docEntry,
          'DocNum': quotputaval!.docNum,
          'DocType': quotputaval!.docType,
          'HandWritten': quotputaval!.handWritten,
          'Printed': quotputaval!.printed,
          'DocDate': quotputaval!.docDate,
          // "${docDate.year.toString().padLeft(4, '0')}-${docDate.month.toString().padLeft(2, '0')}-${docDate.day.toString().padLeft(2, '0')}",
          'DocDueDate': quotputaval!.docDueDate,
          //  "${docDueDate.year.toString().padLeft(4, '0')}-${docDueDate.month.toString().padLeft(2, '0')}-${docDueDate.day.toString().padLeft(2, '0')}",
          'CardCode': "$cardCodePost",
          'CardName': quotputaval!.cardName,
          'Address': quotputaval!.address,
          'NumAtCard': quotputaval!.numAtCard,
          'DocTotal': quotputaval!.docTotal,
          'AttachmentEntry': quotputaval!.attachmentEntry,
          'DocCurrency': quotputaval!.docCurrency,
          'DocRate': quotputaval!.docRate,
          'Reference1': quotputaval!.reference1,
          'Reference2': quotputaval!.reference2,
          'Comments': quotputaval!.comments,
          'JournalMemo': quotputaval!.journalMemo,
          'PaymentGroupCode': quotputaval!.paymentGroupCode,
          'DocTime': quotputaval!.docTime,
          'SalesPersonCode': quotputaval!.salesPersonCode,
          'TransportationCode': quotputaval!.transportationCode,
          'Confirmed': quotputaval!.confirmed,
          'ImportFileNum': quotputaval!.importFileNum,
          'SummeryType': quotputaval!.summeryType,
          'ContactPersonCode': quotputaval!.contactPersonCode,
          'ShowSCN': quotputaval!.showScn,
          'Series': quotputaval!.series,
          'TaxDate': quotputaval!.taxDate,
          // ${taxDate.year.toString().padLeft(4, '0')}-${taxDate.month.toString().padLeft(2, '0')}-${taxDate.day.toString().padLeft(2, '0')}",
          'PartialSupply': quotputaval!.partialSupply,
          'DocObjectCode': quotputaval!.docObjectCode,
          'ShipToCode': quotputaval!.shipToCode == null ||
                  quotputaval!.shipToCode == "null"
              ? null
              : quotputaval!.shipToCode,
          'Indicator': quotputaval!.indicator,
          'FederalTaxID': quotputaval!.federalTaxId == null ||
                  quotputaval!.federalTaxId == "null"
              ? null
              : quotputaval!.federalTaxId,
          'DiscountPercent': quotputaval!.discountPercent,
          'PaymentReference': quotputaval!.paymentReference,
          'CreationDate': "${quotputaval!.creationDate!}",
          'UpdateDate': "${quotputaval!.updateDate}",
          'FinancialPeriod': quotputaval!.financialPeriod,
          'UserSign': quotputaval!.userSign,
          'TransNum': quotputaval!.transNum,
          'VatSum': quotputaval!.vatSum,
          'VatSumSys': quotputaval!.vatSumSys,
          'VatSumFc': quotputaval!.vatSumFc,
          'NetProcedure': quotputaval!.netProcedure,
          'DocTotalFc': quotputaval!.docTotalFc,
          'DocTotalSys': quotputaval!.docTotalSys,
          'Form1099': quotputaval!.form1099,
          'Box1099': quotputaval!.box1099,
          'RevisionPo': quotputaval!.revisionPo,
          'RequriedDate': quotputaval!.requriedDate,
          'CancelDate': quotputaval!.cancelDate,
          'BlockDunning': quotputaval!.blockDunning,
          'Submitted': quotputaval!.submitted,
          'Segment': quotputaval!.segment,
          'PickStatus': quotputaval!.pickStatus,
          'Pick': quotputaval!.pick,
          'PaymentMethod': quotputaval!.paymentMethod,
          'PaymentBlock': quotputaval!.paymentBlock,
          'PaymentBlockEntry': quotputaval!.paymentBlockEntry,
          'CentralBankIndicator': quotputaval!.centralBankIndicator,
          'MaximumCashDiscount': quotputaval!.maximumCashDiscount,
          'Reserve': quotputaval!.reserve,
          'Project': quotputaval!.project,
          'ExemptionValidityDateFrom': quotputaval!.exemptionValidityDateFrom,
          'ExemptionValidityDateTo': quotputaval!.exemptionValidityDateTo,
          'WareHouseUpdateType': quotputaval!.wareHouseUpdateType,
          'Rounding': quotputaval!.rounding,
          'ExternalCorrectedDocNum': quotputaval!.externalCorrectedDocNum,
          'InternalCorrectedDocNum': quotputaval!.internalCorrectedDocNum,
          'NextCorrectingDocument': quotputaval!.nextCorrectingDocument,
          'DeferredTax': quotputaval!.deferredTax,
          'TaxExemptionLetterNum': quotputaval!.taxExemptionLetterNum,
          'WTApplied': quotputaval!.wtApplied,
          'WTAppliedFC': quotputaval!.wtAppliedFc,
          'BillOfExchangeReserved': quotputaval!.billOfExchangeReserved,
          'AgentCode': quotputaval!.agentCode,
          'WTAppliedSC': quotputaval!.wtAppliedSc,
          'TotalEqualizationTax': quotputaval!.totalEqualizationTax,
          'TotalEqualizationTaxFC': quotputaval!.totalEqualizationTaxFc,
          'TotalEqualizationTaxSC': quotputaval!.totalEqualizationTaxSc,
          'NumberOfInstallments': quotputaval!.numberOfInstallments,
          'ApplyTaxOnFirstInstallment': quotputaval!.applyTaxOnFirstInstallment,
          'WTNonSubjectAmount': quotputaval!.wtNonSubjectAmount,
          'WTNonSubjectAmountSC': quotputaval!.wtNonSubjectAmountSc,
          'WTNonSubjectAmountFC': quotputaval!.wtNonSubjectAmountFc,
          'WTExemptedAmount': quotputaval!.wtExemptedAmount,
          'WTExemptedAmountSC': quotputaval!.wtExemptedAmountSc,
          'WTExemptedAmountFC': quotputaval!.wtExemptedAmountFc,
          'BaseAmount': quotputaval!.baseAmount,
          'BaseAmountSC': quotputaval!.baseAmountSc,
          'BaseAmountFC': quotputaval!.baseAmountFc,
          'WTAmount': quotputaval!.wtAmount,
          'WTAmountSC': quotputaval!.wtAmountSc,
          'WTAmountFC': quotputaval!.wtAmountFc,
          'VatDate': quotputaval!.vatDate,
          'DocumentsOwner': quotputaval!.documentsOwner,
          'FolioPrefixString': quotputaval!.folioPrefixString,
          'FolioNumber': quotputaval!.folioNumber,
          'DocumentSubType': quotputaval!.documentSubType,
          'BPChannelCode': quotputaval!.bpChannelCode,
          'BPChannelContact': quotputaval!.bpChannelContact,
          'Address2': quotputaval!.address2,
          'DocumentStatus': quotputaval!.documentStatus,
          'PeriodIndicator': quotputaval!.periodIndicator,
          'PayToCode': quotputaval!.payToCode,
          'ManualNumber': quotputaval!.manualNumber,
          'UseShpdGoodsAct': quotputaval!.useShpdGoodsAct,
          'IsPayToBank': quotputaval!.isPayToBank,
          'PayToBankCountry': quotputaval!.payToBankCountry,
          'PayToBankCode': quotputaval!.payToBankCode,
          'PayToBankAccountNo': quotputaval!.payToBankAccountNo,
          'PayToBankBranch': quotputaval!.payToBankBranch,
          'BPL_IDAssignedToInvoice': quotputaval!.bplIdAssignedToInvoice,
          'DownPayment': quotputaval!.downPayment,
          'ReserveInvoice': quotputaval!.reserveInvoice,
          'LanguageCode': quotputaval!.languageCode,
          'TrackingNumber': quotputaval!.trackingNumber,
          'PickRemark': quotputaval!.pickRemark,
          'ClosingDate': quotputaval!.closingDate,
          'SequenceCode': quotputaval!.sequenceCode,
          'SequenceSerial': quotputaval!.sequenceSerial,
          'SeriesString': quotputaval!.seriesString,
          'SubSeriesString': quotputaval!.subSeriesString,
          'SequenceModel': quotputaval!.sequenceModel,
          'UseCorrectionVATGroup': quotputaval!.useCorrectionVatGroup,
          'TotalDiscount': quotputaval!.totalDiscount,
          'DownPaymentAmount': quotputaval!.downPaymentAmount,
          'DownPaymentPercentage': quotputaval!.downPaymentPercentage,
          'DownPaymentType': quotputaval!.downPaymentType,
          'DownPaymentAmountSC': quotputaval!.downPaymentAmountSc,
          'DownPaymentAmountFC': quotputaval!.downPaymentAmountFc,
          'VatPercent': quotputaval!.vatPercent,
          'ServiceGrossProfitPercent': quotputaval!.serviceGrossProfitPercent,
          'OpeningRemarks': quotputaval!.openingRemarks,
          'ClosingRemarks': quotputaval!.closingRemarks,
          'RoundingDiffAmount': quotputaval!.roundingDiffAmount,
          'RoundingDiffAmountFC': quotputaval!.roundingDiffAmountFc,
          'RoundingDiffAmountSC': quotputaval!.roundingDiffAmountSc,
          'Cancelled': quotputaval!.cancelled,
          'SignatureInputMessage': quotputaval!.signatureInputMessage,
          'SignatureDigest': quotputaval!.signatureDigest,
          'CertificationNumber': quotputaval!.certificationNumber,
          'PrivateKeyVersion': quotputaval!.privateKeyVersion,
          'ControlAccount': quotputaval!.controlAccount,
          'InsuranceOperation347': quotputaval!.insuranceOperation347,
          'ArchiveNonremovableSalesQuotation':
              quotputaval!.archiveNonremovableSalesQuotation,
          'GTSChecker': quotputaval!.gtsChecker,
          'GTSPayee': quotputaval!.gtsPayee,
          'ExtraMonth': quotputaval!.extraMonth,
          'ExtraDays': quotputaval!.extraDays,
          'CashDiscountDateOffset': quotputaval!.cashDiscountDateOffset,
          'StartFrom': quotputaval!.startFrom,
          'NTSApproved': quotputaval!.ntsApproved,
          'ETaxWebSite': quotputaval!.eTaxWebSite,
          'ETaxNumber': quotputaval!.eTaxNumber,
          'NTSApprovedNumber': quotputaval!.ntsApprovedNumber,
          'EDocGenerationType': quotputaval!.eDocGenerationType,
          'EDocSeries': quotputaval!.eDocSeries,
          'EDocNum': quotputaval!.eDocNum,
          'EDocExportFormat': quotputaval!.eDocExportFormat,
          'EDocStatus': quotputaval!.eDocStatus,
          'EDocErrorCode': quotputaval!.eDocErrorCode,
          'EDocErrorMessage': quotputaval!.eDocErrorMessage,
          'DownPaymentStatus': quotputaval!.downPaymentStatus,
          'GroupSeries': quotputaval!.groupSeries,
          'GroupNumber': quotputaval!.groupNumber,
          'GroupHandWritten': quotputaval!.groupHandWritten,
          'ReopenOriginalDocument': quotputaval!.reopenOriginalDocument,
          'ReopenManuallyClosedOrCanceledDocument':
              quotputaval!.reopenManuallyClosedOrCanceledDocument,
          'CreateOnlineQuotation': quotputaval!.createOnlineQuotation,
          'POSEquipmentNumber': quotputaval!.posEquipmentNumber,
          'POSManufacturerSerialNumber':
              quotputaval!.posManufacturerSerialNumber,
          'POSCashierNumber': quotputaval!.posCashierNumber,
          'ApplyCurrentVATRatesForDownPaymentsToDraw':
              quotputaval!.applyCurrentVatRatesForDownPaymentsToDraw,
          'ClosingOption': quotputaval!.closingOption,
          'SpecifiedClosingDate': quotputaval!.specifiedClosingDate,
          'OpenForLandedCosts': quotputaval!.openForLandedCosts,
          'AuthorizationStatus': quotputaval!.authorizationStatus,
          'TotalDiscountFC': quotputaval!.totalDiscountFc,
          'TotalDiscountSC': quotputaval!.totalDiscountSc,
          'RelevantToGTS': quotputaval!.relevantToGts,
          'BPLName': quotputaval!.bplName,
          'VATRegNum': quotputaval!.vatRegNum,
          'AnnualInvoiceDeclarationReference':
              quotputaval!.annualInvoiceDeclarationReference,
          'Supplier': quotputaval!.supplier,
          'Releaser': quotputaval!.releaser,
          'Receiver': quotputaval!.receiver,
          'BlanketAgreementNumber': quotputaval!.blanketAgreementNumber,
          'IsAlteration': quotputaval!.isAlteration,
          'CancelStatus': quotputaval!.cancelStatus,
          'AssetValueDate': quotputaval!.assetValueDate,
          'DocumentDelivery': quotputaval!.documentDelivery,
          'AuthorizationCode': quotputaval!.authorizationCode,
          'StartDeliveryDate': quotputaval!.startDeliveryDate,
          'StartDeliveryTime': quotputaval!.startDeliveryTime,
          'EndDeliveryDate': quotputaval!.endDeliveryDate,
          'EndDeliveryTime': quotputaval!.endDeliveryTime,
          'VehiclePlate': quotputaval!.vehiclePlate,
          'ATDocumentType': quotputaval!.atDocumentType,
          'ElecCommStatus': quotputaval!.elecCommStatus,
          'ElecCommMessage': quotputaval!.elecCommMessage,
          'ReuseDocumentNum': quotputaval!.reuseDocumentNum,
          'ReuseNotaFiscalNum': quotputaval!.reuseNotaFiscalNum,
          'PrintSEPADirect': quotputaval!.printSepaDirect,
          'FiscalDocNum': quotputaval!.fiscalDocNum,
          'POSDailySummaryNo': quotputaval!.posDailySummaryNo,
          'POSReceiptNo': quotputaval!.posReceiptNo,
          'PointOfIssueCode': quotputaval!.pointOfIssueCode,
          'Letter': quotputaval!.letter,
          'FolioNumberFrom': quotputaval!.folioNumberFrom,
          'FolioNumberTo': quotputaval!.folioNumberTo,
          'InterimType': quotputaval!.interimType,
          'RelatedType': quotputaval!.relatedType,
          'RelatedEntry': quotputaval!.relatedEntry,
          'SAPPassport': quotputaval!.sapPassport,
          'DocumentTaxID': quotputaval!.documentTaxId,
          'DateOfReportingControlStatementVAT':
              quotputaval!.dateOfReportingControlStatementVat,
          'ReportingSectionControlStatementVAT':
              quotputaval!.reportingSectionControlStatementVat,
          'ExcludeFromTaxReportControlStatementVAT':
              quotputaval!.excludeFromTaxReportControlStatementVat,
          'POS_CashRegister': quotputaval!.posCashRegister,
          'UpdateTime': quotputaval!.updateTime,
          'CreateQRCodeFrom': quotputaval!.createQrCodeFrom,
          'PriceMode': quotputaval!.priceMode,
          'ShipFrom': quotputaval!.shipFrom,
          'CommissionTrade': quotputaval!.commissionTrade,
          'CommissionTradeReturn': quotputaval!.commissionTradeReturn,
          'UseBillToAddrToDetermineTax':
              quotputaval!.useBillToAddrToDetermineTax,
          'Cig': quotputaval!.cig,
          'Cup': quotputaval!.cup,
          'FatherCard': quotputaval!.fatherCard,
          'FatherType': quotputaval!.fatherType,
          'ShipState': quotputaval!.shipState,
          'ShipPlace': quotputaval!.shipPlace,
          'CustOffice': quotputaval!.custOffice,
          'FCI': quotputaval!.fci,
          'AddLegIn': quotputaval!.addLegIn,
          'LegTextF': quotputaval!.legTextF,
          'DANFELgTxt': quotputaval!.danfeLgTxt,
          'IndFinal': quotputaval!.indFinal,
          'DataVersion': quotputaval!.dataVersion,
          'U_Purchase_Type': quotputaval!.uPurchaseType,
          'U_AP_Approve': quotputaval!.uApApprove,
          'U_Final_Del': quotputaval!.uFinalDel,
          'U_Inco_Terms': quotputaval!.uIncoTerms,
          'U_Source_Dest': quotputaval!.uSourceDest,
          'U_Trans_NO': quotputaval!.uTransNo,
          'U_Vehicle_NO': quotputaval!.uVehicleNo,
          'U_Supplier_DT': quotputaval!.uSupplierDt,
          'U_QuotNo': quotputaval!.uQuotNo,
          'U_QuotDate': quotputaval!.uQuotDate,
          'U_GovPermit': quotputaval!.uGovPermit,
          'U_GovPermitdt': quotputaval!.uGovPermitdt,
          'U_CheckNo': quotputaval!.uCheckNo,
          'U_CheckDate': quotputaval!.uCheckDate,
          'U_ApprovalDate': quotputaval!.uApprovalDate,
          'U_OrderNoRecd': quotputaval!.uOrderNoRecd,
          'U_OrderDate': quotputaval!.uOrderDate,
          'U_ClearingAgent': quotputaval!.uClearingAgent,
          'U_DateSubAgent': quotputaval!.uDateSubAgent,
          'U_IDFNO': quotputaval!.uIdfno,
          'U_IDFDate': quotputaval!.uIdfDate,
          'U_InspectionNo': quotputaval!.uInspectionNo,
          'U_ETA': quotputaval!.uEta,
          'U_AirwayBillNo': quotputaval!.uAirwayBillNo,
          'U_BOL': quotputaval!.uBol,
          'U_Cotecna': quotputaval!.uCotecna,
          'U_ArrivalDate': quotputaval!.uArrivalDate,
          'U_DahacoAgentFees': quotputaval!.uDahacoAgentFees,
          'U_PortCharges': quotputaval!.uPortCharges,
          'U_OtherExp': quotputaval!.uOtherExp,
          'U_ClearCharges': quotputaval!.uClearCharges,
          'U_HiddenChrges': quotputaval!.uHiddenChrges,
          'U_GoodsInspBy': quotputaval!.uGoodsInspBy,
          'U_GoodsReport': quotputaval!.uGoodsReport,
          'U_PymtStatus': quotputaval!.uPymtStatus,
          'U_PymtType': quotputaval!.uPymtType,
          'U_TTCopyImage': quotputaval!.uTtCopyImage,
          'U_PFI_Image': quotputaval!.uPfiImage,
          'U_Supplier_Image': quotputaval!.uSupplierImage,
          'U_BOL_Image': quotputaval!.uBolImage,
          'U_Order_Type': quotputaval!.uOrderType,
          'U_Truck_Internal': quotputaval!.uTruckInternal,
          'U_GP_Approval': quotputaval!.uGpApproval,
          'U_SUPPLIER_NAME': quotputaval!.uSupplierName,
          'U_VAT_NUMBER': quotputaval!.uVatNumber,
          'U_Transfer_Type': quotputaval!.uTransferType,
          'U_Sales_Order': quotputaval!.uSalesOrder,
          'U_Received': quotputaval!.uReceived,
          'U_Driver_Name': quotputaval!.uDriverName,
          'U_Reserve_Invoice': quotputaval!.uReserveInvoice,
          'U_Ref_Series': quotputaval!.uRefSeries,
          'U_Received_Time': quotputaval!.uReceivedTime,
          'U_SKU_Batch_No': quotputaval!.uSkuBatchNo,
          'U_Inward_No': quotputaval!.uInwardNo,
          'U_Dispatch_Time': quotputaval!.uDispatchTime,
          'U_Received_Date': quotputaval!.uReceivedDate,
          'U_Expiry_Date': quotputaval!.uExpiryDate,
          'U_CN_Type': quotputaval!.uCnType,
          'U_TinNO': quotputaval!.uTinNo,
          'U_LPONo': quotputaval!.uLpoNo,
          'U_OrderQty': quotputaval!.uOrderQty,
          'U_Dispatch_Date': quotputaval!.uDispatchDate,
          'U_Branch': quotputaval!.uBranch,
          'U_SalAppEntry': quotputaval!.uSalAppEntry,
          'U_DocType': quotputaval!.uDocType,
          'U_IntKey': quotputaval!.uIntKey,
          'U_QRFileLoc': quotputaval!.uQrFileLoc,
          'U_rctCde': quotputaval!.uRctCde,
          'U_Zno': quotputaval!.uZno,
          'U_VfdIn': quotputaval!.uVfdIn,
          'U_QRPath': quotputaval!.uQrPath,
          'U_QRValue': quotputaval!.uQrValue,
          'U_idate': quotputaval!.uIdate,
          'U_itime': quotputaval!.uItime,
          'U_DeviceCode': quotputaval!.uDeviceCode,
          'U_DeviceTransID': quotputaval!.uDeviceTransId,
          'U_RVC': quotputaval!.uRvc,
          'U_VRN': quotputaval!.uVrn,
          'U_longitude': quotputaval!.uLongitude,
          'U_latitude': quotputaval!.uLatitude,
          'U_AUDIT_JOB_GROUP': quotputaval!.uAuditJobGroup,
          'U_AUDIT_NAME': quotputaval!.uAuditName,
          'U_Request': quotputaval!.uRequest,
          'U_PosDocNo': quotputaval!.uPosDocNo,
          'TaxExtension': quotputaval!.taxExtension,
          'AddressExtension': quotputaval!.addressExtension,
          "DocumentReferences": quotputaval!.documentReferences,
          "DocumentLines": docLineQout!.map((e) => e.toJson()).toList(),
          "Document_ApprovalRequests": [],
          "ElectronicProtocols": [],
          "DocumentAdditionalExpenses": [],
          "DocumentSpecialLines": []
        }),
      );
      log("statucCode QUT EDITS: " + response.statusCode.toString());
  
      log(
        "datatatat: " +
            json.encode({
              'odata.metadata': quotputaval!.odataMetadata,
              'odata.etag': quotputaval!.odataEtag,
              'DocEntry': quotputaval!.docEntry,
              'DocNum': quotputaval!.docNum,
              'DocType': quotputaval!.docType,
              'HandWritten': quotputaval!.handWritten,
              'Printed': quotputaval!.printed,
              'DocDate': quotputaval!.docDate,
              // "${docDate.year.toString().padLeft(4, '0')}-${docDate.month.toString().padLeft(2, '0')}-${docDate.day.toString().padLeft(2, '0')}",
              'DocDueDate': quotputaval!.docDueDate,
              //  "${docDueDate.year.toString().padLeft(4, '0')}-${docDueDate.month.toString().padLeft(2, '0')}-${docDueDate.day.toString().padLeft(2, '0')}",
              'CardCode': "$cardCodePost",
              'CardName': quotputaval!.cardName,
              'Address': quotputaval!.address,
              'NumAtCard': quotputaval!.numAtCard,
              'DocTotal': quotputaval!.docTotal,
              'AttachmentEntry': quotputaval!.attachmentEntry,
              'DocCurrency': quotputaval!.docCurrency,
              'DocRate': quotputaval!.docRate,
              'Reference1': quotputaval!.reference1,
              'Reference2': quotputaval!.reference2,
              'Comments': "$remarks",
              'JournalMemo': quotputaval!.journalMemo,
              'PaymentGroupCode': quotputaval!.paymentGroupCode,
              'DocTime': quotputaval!.docTime,
              'SalesPersonCode': quotputaval!.salesPersonCode,
              'TransportationCode': quotputaval!.transportationCode,
              'Confirmed': quotputaval!.confirmed,
              'ImportFileNum': quotputaval!.importFileNum,
              'SummeryType': quotputaval!.summeryType,
              'ContactPersonCode': quotputaval!.contactPersonCode,
              'ShowSCN': quotputaval!.showScn,
              'Series': quotputaval!.series,
              'TaxDate': quotputaval!.taxDate,
              // config2.currentDate(),
              // ${taxDate.year.toString().padLeft(4, '0')}-${taxDate.month.toString().padLeft(2, '0')}-${taxDate.day.toString().padLeft(2, '0')}",
              'PartialSupply': quotputaval!.partialSupply,
              'DocObjectCode': quotputaval!.docObjectCode,
              'ShipToCode': quotputaval!.shipToCode,
              'Indicator': quotputaval!.indicator,
              'FederalTaxID': quotputaval!.federalTaxId,
              'DiscountPercent': quotputaval!.discountPercent,
              'PaymentReference': quotputaval!.paymentReference,
              'CreationDate': "${quotputaval!.creationDate!}",
              'UpdateDate': "${quotputaval!.updateDate}",
              'FinancialPeriod': quotputaval!.financialPeriod,
              'UserSign': quotputaval!.userSign,
              'TransNum': quotputaval!.transNum,
              'VatSum': quotputaval!.vatSum,
              'VatSumSys': quotputaval!.vatSumSys,
              'VatSumFc': quotputaval!.vatSumFc,
              'NetProcedure': quotputaval!.netProcedure,
              'DocTotalFc': quotputaval!.docTotalFc,
              'DocTotalSys': quotputaval!.docTotalSys,
              'Form1099': quotputaval!.form1099,
              'Box1099': quotputaval!.box1099,
              'RevisionPo': quotputaval!.revisionPo,
              'RequriedDate': quotputaval!.requriedDate,
              'CancelDate': quotputaval!.cancelDate,
              'BlockDunning': quotputaval!.blockDunning,
              'Submitted': quotputaval!.submitted,
              'Segment': quotputaval!.segment,
              'PickStatus': quotputaval!.pickStatus,
              'Pick': quotputaval!.pick,
              'PaymentMethod': quotputaval!.paymentMethod,
              'PaymentBlock': quotputaval!.paymentBlock,
              'PaymentBlockEntry': quotputaval!.paymentBlockEntry,
              'CentralBankIndicator': quotputaval!.centralBankIndicator,
              'MaximumCashDiscount': quotputaval!.maximumCashDiscount,
              'Reserve': quotputaval!.reserve,
              'Project': quotputaval!.project,
              'ExemptionValidityDateFrom':
                  quotputaval!.exemptionValidityDateFrom,
              'ExemptionValidityDateTo': quotputaval!.exemptionValidityDateTo,
              'WareHouseUpdateType': quotputaval!.wareHouseUpdateType,
              'Rounding': quotputaval!.rounding,
              'ExternalCorrectedDocNum': quotputaval!.externalCorrectedDocNum,
              'InternalCorrectedDocNum': quotputaval!.internalCorrectedDocNum,
              'NextCorrectingDocument': quotputaval!.nextCorrectingDocument,
              'DeferredTax': quotputaval!.deferredTax,
              'TaxExemptionLetterNum': quotputaval!.taxExemptionLetterNum,
              'WTApplied': quotputaval!.wtApplied,
              'WTAppliedFC': quotputaval!.wtAppliedFc,
              'BillOfExchangeReserved': quotputaval!.billOfExchangeReserved,
              'AgentCode': quotputaval!.agentCode,
              'WTAppliedSC': quotputaval!.wtAppliedSc,
              'TotalEqualizationTax': quotputaval!.totalEqualizationTax,
              'TotalEqualizationTaxFC': quotputaval!.totalEqualizationTaxFc,
              'TotalEqualizationTaxSC': quotputaval!.totalEqualizationTaxSc,
              'NumberOfInstallments': quotputaval!.numberOfInstallments,
              'ApplyTaxOnFirstInstallment':
                  quotputaval!.applyTaxOnFirstInstallment,
              'WTNonSubjectAmount': quotputaval!.wtNonSubjectAmount,
              'WTNonSubjectAmountSC': quotputaval!.wtNonSubjectAmountSc,
              'WTNonSubjectAmountFC': quotputaval!.wtNonSubjectAmountFc,
              'WTExemptedAmount': quotputaval!.wtExemptedAmount,
              'WTExemptedAmountSC': quotputaval!.wtExemptedAmountSc,
              'WTExemptedAmountFC': quotputaval!.wtExemptedAmountFc,
              'BaseAmount': quotputaval!.baseAmount,
              'BaseAmountSC': quotputaval!.baseAmountSc,
              'BaseAmountFC': quotputaval!.baseAmountFc,
              'WTAmount': quotputaval!.wtAmount,
              'WTAmountSC': quotputaval!.wtAmountSc,
              'WTAmountFC': quotputaval!.wtAmountFc,
              'VatDate': quotputaval!.vatDate,
              'DocumentsOwner': quotputaval!.documentsOwner,
              'FolioPrefixString': quotputaval!.folioPrefixString,
              'FolioNumber': quotputaval!.folioNumber,
              'DocumentSubType': quotputaval!.documentSubType,
              'BPChannelCode': quotputaval!.bpChannelCode,
              'BPChannelContact': quotputaval!.bpChannelContact,
              'Address2': quotputaval!.address2,
              'DocumentStatus': quotputaval!.documentStatus,
              'PeriodIndicator': quotputaval!.periodIndicator,
              'PayToCode': quotputaval!.payToCode,
              'ManualNumber': quotputaval!.manualNumber,
              'UseShpdGoodsAct': quotputaval!.useShpdGoodsAct,
              'IsPayToBank': quotputaval!.isPayToBank,
              'PayToBankCountry': quotputaval!.payToBankCountry,
              'PayToBankCode': quotputaval!.payToBankCode,
              'PayToBankAccountNo': quotputaval!.payToBankAccountNo,
              'PayToBankBranch': quotputaval!.payToBankBranch,
              'BPL_IDAssignedToInvoice': quotputaval!.bplIdAssignedToInvoice,
              'DownPayment': quotputaval!.downPayment,
              'ReserveInvoice': quotputaval!.reserveInvoice,
              'LanguageCode': quotputaval!.languageCode,
              'TrackingNumber': quotputaval!.trackingNumber,
              'PickRemark': quotputaval!.pickRemark,
              'ClosingDate': quotputaval!.closingDate,
              'SequenceCode': quotputaval!.sequenceCode,
              'SequenceSerial': quotputaval!.sequenceSerial,
              'SeriesString': quotputaval!.seriesString,
              'SubSeriesString': quotputaval!.subSeriesString,
              'SequenceModel': quotputaval!.sequenceModel,
              'UseCorrectionVATGroup': quotputaval!.useCorrectionVatGroup,
              'TotalDiscount': quotputaval!.totalDiscount,
              'DownPaymentAmount': quotputaval!.downPaymentAmount,
              'DownPaymentPercentage': quotputaval!.downPaymentPercentage,
              'DownPaymentType': quotputaval!.downPaymentType,
              'DownPaymentAmountSC': quotputaval!.downPaymentAmountSc,
              'DownPaymentAmountFC': quotputaval!.downPaymentAmountFc,
              'VatPercent': quotputaval!.vatPercent,
              'ServiceGrossProfitPercent':
                  quotputaval!.serviceGrossProfitPercent,
              'OpeningRemarks': quotputaval!.openingRemarks,
              'ClosingRemarks': quotputaval!.closingRemarks,
              'RoundingDiffAmount': quotputaval!.roundingDiffAmount,
              'RoundingDiffAmountFC': quotputaval!.roundingDiffAmountFc,
              'RoundingDiffAmountSC': quotputaval!.roundingDiffAmountSc,
              'Cancelled': quotputaval!.cancelled,
              'SignatureInputMessage': quotputaval!.signatureInputMessage,
              'SignatureDigest': quotputaval!.signatureDigest,
              'CertificationNumber': quotputaval!.certificationNumber,
              'PrivateKeyVersion': quotputaval!.privateKeyVersion,
              'ControlAccount': quotputaval!.controlAccount,
              'InsuranceOperation347': quotputaval!.insuranceOperation347,
              'ArchiveNonremovableSalesQuotation':
                  quotputaval!.archiveNonremovableSalesQuotation,
              'GTSChecker': quotputaval!.gtsChecker,
              'GTSPayee': quotputaval!.gtsPayee,
              'ExtraMonth': quotputaval!.extraMonth,
              'ExtraDays': quotputaval!.extraDays,
              'CashDiscountDateOffset': quotputaval!.cashDiscountDateOffset,
              'StartFrom': quotputaval!.startFrom,
              'NTSApproved': quotputaval!.ntsApproved,
              'ETaxWebSite': quotputaval!.eTaxWebSite,
              'ETaxNumber': quotputaval!.eTaxNumber,
              'NTSApprovedNumber': quotputaval!.ntsApprovedNumber,
              'EDocGenerationType': quotputaval!.eDocGenerationType,
              'EDocSeries': quotputaval!.eDocSeries,
              'EDocNum': quotputaval!.eDocNum,
              'EDocExportFormat': quotputaval!.eDocExportFormat,
              'EDocStatus': quotputaval!.eDocStatus,
              'EDocErrorCode': quotputaval!.eDocErrorCode,
              'EDocErrorMessage': quotputaval!.eDocErrorMessage,
              'DownPaymentStatus': quotputaval!.downPaymentStatus,
              'GroupSeries': quotputaval!.groupSeries,
              'GroupNumber': quotputaval!.groupNumber,
              'GroupHandWritten': quotputaval!.groupHandWritten,
              'ReopenOriginalDocument': quotputaval!.reopenOriginalDocument,
              'ReopenManuallyClosedOrCanceledDocument':
                  quotputaval!.reopenManuallyClosedOrCanceledDocument,
              'CreateOnlineQuotation': quotputaval!.createOnlineQuotation,
              'POSEquipmentNumber': quotputaval!.posEquipmentNumber,
              'POSManufacturerSerialNumber':
                  quotputaval!.posManufacturerSerialNumber,
              'POSCashierNumber': quotputaval!.posCashierNumber,
              'ApplyCurrentVATRatesForDownPaymentsToDraw':
                  quotputaval!.applyCurrentVatRatesForDownPaymentsToDraw,
              'ClosingOption': quotputaval!.closingOption,
              'SpecifiedClosingDate': quotputaval!.specifiedClosingDate,
              'OpenForLandedCosts': quotputaval!.openForLandedCosts,
              'AuthorizationStatus': quotputaval!.authorizationStatus,
              'TotalDiscountFC': quotputaval!.totalDiscountFc,
              'TotalDiscountSC': quotputaval!.totalDiscountSc,
              'RelevantToGTS': quotputaval!.relevantToGts,
              'BPLName': quotputaval!.bplName,
              'VATRegNum': quotputaval!.vatRegNum,
              'AnnualInvoiceDeclarationReference':
                  quotputaval!.annualInvoiceDeclarationReference,
              'Supplier': quotputaval!.supplier,
              'Releaser': quotputaval!.releaser,
              'Receiver': quotputaval!.receiver,
              'BlanketAgreementNumber': quotputaval!.blanketAgreementNumber,
              'IsAlteration': quotputaval!.isAlteration,
              'CancelStatus': quotputaval!.cancelStatus,
              'AssetValueDate': quotputaval!.assetValueDate,
              'DocumentDelivery': quotputaval!.documentDelivery,
              'AuthorizationCode': quotputaval!.authorizationCode,
              'StartDeliveryDate': quotputaval!.startDeliveryDate,
              'StartDeliveryTime': quotputaval!.startDeliveryTime,
              'EndDeliveryDate': quotputaval!.endDeliveryDate,
              'EndDeliveryTime': quotputaval!.endDeliveryTime,
              'VehiclePlate': quotputaval!.vehiclePlate,
              'ATDocumentType': quotputaval!.atDocumentType,
              'ElecCommStatus': quotputaval!.elecCommStatus,
              'ElecCommMessage': quotputaval!.elecCommMessage,
              'ReuseDocumentNum': quotputaval!.reuseDocumentNum,
              'ReuseNotaFiscalNum': quotputaval!.reuseNotaFiscalNum,
              'PrintSEPADirect': quotputaval!.printSepaDirect,
              'FiscalDocNum': quotputaval!.fiscalDocNum,
              'POSDailySummaryNo': quotputaval!.posDailySummaryNo,
              'POSReceiptNo': quotputaval!.posReceiptNo,
              'PointOfIssueCode': quotputaval!.pointOfIssueCode,
              'Letter': quotputaval!.letter,
              'FolioNumberFrom': quotputaval!.folioNumberFrom,
              'FolioNumberTo': quotputaval!.folioNumberTo,
              'InterimType': quotputaval!.interimType,
              'RelatedType': quotputaval!.relatedType,
              'RelatedEntry': quotputaval!.relatedEntry,
              'SAPPassport': quotputaval!.sapPassport,
              'DocumentTaxID': quotputaval!.documentTaxId,
              'DateOfReportingControlStatementVAT':
                  quotputaval!.dateOfReportingControlStatementVat,
              'ReportingSectionControlStatementVAT':
                  quotputaval!.reportingSectionControlStatementVat,
              'ExcludeFromTaxReportControlStatementVAT':
                  quotputaval!.excludeFromTaxReportControlStatementVat,
              'POS_CashRegister': quotputaval!.posCashRegister,
              'UpdateTime': quotputaval!.updateTime,
              'CreateQRCodeFrom': quotputaval!.createQrCodeFrom,
              'PriceMode': quotputaval!.priceMode,
              'ShipFrom': quotputaval!.shipFrom,
              'CommissionTrade': quotputaval!.commissionTrade,
              'CommissionTradeReturn': quotputaval!.commissionTradeReturn,
              'UseBillToAddrToDetermineTax':
                  quotputaval!.useBillToAddrToDetermineTax,
              'Cig': quotputaval!.cig,
              'Cup': quotputaval!.cup,
              'FatherCard': quotputaval!.fatherCard,
              'FatherType': quotputaval!.fatherType,
              'ShipState': quotputaval!.shipState,
              'ShipPlace': quotputaval!.shipPlace,
              'CustOffice': quotputaval!.custOffice,
              'FCI': quotputaval!.fci,
              'AddLegIn': quotputaval!.addLegIn,
              'LegTextF': quotputaval!.legTextF,
              'DANFELgTxt': quotputaval!.danfeLgTxt,
              'IndFinal': quotputaval!.indFinal,
              'DataVersion': quotputaval!.dataVersion,

              'U_Purchase_Type': quotputaval!.uPurchaseType,
              'U_AP_Approve': quotputaval!.uApApprove,
              'U_Final_Del': quotputaval!.uFinalDel,
              'U_Inco_Terms': quotputaval!.uIncoTerms,
              'U_Source_Dest': quotputaval!.uSourceDest,
              'U_Trans_NO': quotputaval!.uTransNo,
              'U_Vehicle_NO': quotputaval!.uVehicleNo,
              'U_Supplier_DT': quotputaval!.uSupplierDt,
              'U_QuotNo': quotputaval!.uQuotNo,
              'U_QuotDate': quotputaval!.uQuotDate,
              'U_GovPermit': quotputaval!.uGovPermit,
              'U_GovPermitdt': quotputaval!.uGovPermitdt,
              'U_CheckNo': quotputaval!.uCheckNo,
              'U_CheckDate': quotputaval!.uCheckDate,
              'U_ApprovalDate': quotputaval!.uApprovalDate,
              'U_OrderNoRecd': quotputaval!.uOrderNoRecd,
              'U_OrderDate': quotputaval!.uOrderDate,
              'U_ClearingAgent': quotputaval!.uClearingAgent,
              'U_DateSubAgent': quotputaval!.uDateSubAgent,
              'U_IDFNO': quotputaval!.uIdfno,
              'U_IDFDate': quotputaval!.uIdfDate,
              'U_InspectionNo': quotputaval!.uInspectionNo,
              'U_ETA': quotputaval!.uEta,
              'U_AirwayBillNo': quotputaval!.uAirwayBillNo,
              'U_BOL': quotputaval!.uBol,
              'U_Cotecna': quotputaval!.uCotecna,
              'U_ArrivalDate': quotputaval!.uArrivalDate,
              'U_DahacoAgentFees': quotputaval!.uDahacoAgentFees,
              'U_PortCharges': quotputaval!.uPortCharges,
              'U_OtherExp': quotputaval!.uOtherExp,
              'U_ClearCharges': quotputaval!.uClearCharges,
              'U_HiddenChrges': quotputaval!.uHiddenChrges,
              'U_GoodsInspBy': quotputaval!.uGoodsInspBy,
              'U_GoodsReport': quotputaval!.uGoodsReport,
              'U_PymtStatus': quotputaval!.uPymtStatus,
              'U_PymtType': quotputaval!.uPymtType,
              'U_TTCopyImage': quotputaval!.uTtCopyImage,
              'U_PFI_Image': quotputaval!.uPfiImage,
              'U_Supplier_Image': quotputaval!.uSupplierImage,
              'U_BOL_Image': quotputaval!.uBolImage,
              'U_Order_Type': quotputaval!.uOrderType,
              'U_Truck_Internal': quotputaval!.uTruckInternal,
              'U_GP_Approval': quotputaval!.uGpApproval,
              'U_SUPPLIER_NAME': quotputaval!.uSupplierName,
              'U_VAT_NUMBER': quotputaval!.uVatNumber,
              'U_Transfer_Type': quotputaval!.uTransferType,
              'U_Sales_Order': quotputaval!.uSalesOrder,
              'U_Received': quotputaval!.uReceived,
              'U_Driver_Name': quotputaval!.uDriverName,
              'U_Reserve_Invoice': quotputaval!.uReserveInvoice,
              'U_Ref_Series': quotputaval!.uRefSeries,
              'U_Received_Time': quotputaval!.uReceivedTime,
              'U_SKU_Batch_No': quotputaval!.uSkuBatchNo,
              'U_Inward_No': quotputaval!.uInwardNo,
              'U_Dispatch_Time': quotputaval!.uDispatchTime,
              'U_Received_Date': quotputaval!.uReceivedDate,
              'U_Expiry_Date': quotputaval!.uExpiryDate,
              'U_CN_Type': quotputaval!.uCnType,
              'U_TinNO': quotputaval!.uTinNo,
              'U_LPONo': quotputaval!.uLpoNo,
              'U_OrderQty': quotputaval!.uOrderQty,
              'U_Dispatch_Date': quotputaval!.uDispatchDate,
              'U_Branch': quotputaval!.uBranch,
              'U_SalAppEntry': quotputaval!.uSalAppEntry,
              'U_DocType': quotputaval!.uDocType,
              'U_IntKey': quotputaval!.uIntKey,
              'U_QRFileLoc': quotputaval!.uQrFileLoc,
              'U_rctCde': quotputaval!.uRctCde,
              'U_Zno': quotputaval!.uZno,
              'U_VfdIn': quotputaval!.uVfdIn,
              'U_QRPath': quotputaval!.uQrPath,
              'U_QRValue': quotputaval!.uQrValue,
              'U_idate': quotputaval!.uIdate,
              'U_itime': quotputaval!.uItime,
              'U_DeviceCode': quotputaval!.uDeviceCode,
              'U_DeviceTransID': quotputaval!.uDeviceTransId,
              'U_RVC': quotputaval!.uRvc,
              'U_VRN': quotputaval!.uVrn,
              'U_longitude': quotputaval!.uLongitude,
              'U_latitude': quotputaval!.uLatitude,
              'U_AUDIT_JOB_GROUP': quotputaval!.uAuditJobGroup,
              'U_AUDIT_NAME': quotputaval!.uAuditName,
              'U_Request': quotputaval!.uRequest,
              'U_PosDocNo': quotputaval!.uPosDocNo,
              'TaxExtension': quotputaval!.taxExtension,

              'AddressExtension': quotputaval!.addressExtension,
              "Document_ApprovalRequests": [],
              "ElectronicProtocols": [],
              "DocumentAdditionalExpenses": [],
              "DocumentSpecialLines": [],
              "DocumentLines": docLineQout!.map((e) => e.toJson()).toList(),
              "DocumentReferences": quotputaval!.documentReferences
            }),
      );

      if (response.statusCode >= 200 && response.statusCode <= 204) {
        return SalesQuotStatus.fromJson(response.statusCode);
      } else {
            log("Quotations post: " +
          json.decode(response.body.toString()).toString());
        return SalesQuotStatus.errorIN(
            json.decode(response.body) as Map<String, dynamic>,
            response.statusCode);
      }
    } catch (e) {
      log(e.toString());
      //  throw Exception(e);
      return SalesQuotStatus.issue(
          'Restart the app or contact the admin!!..\n');
    }
  }
}
